"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { AnimatePresence, useMotionValueEvent, useReducedMotion, useScroll } from "motion/react";
import * as m from "motion/react-m";
import { Arrow, CloseIcon, SearchIcon } from "./Icons";
import { articles, products } from "@/lib/site-content";
const links = [{label:"Inicio",href:"/"},{label:"Nosotros",href:"/nosotros"},{label:"Productos",href:"/productos"},{label:"Empresas",href:"/estructura"},{label:"Actualidad",href:"/#actualidad"}];
const searchItems = [...products.map(p=>({title:p.name,detail:p.description,href:`/productos?categoria=${p.id}`})),...articles.map(a=>({title:a.title,detail:a.excerpt,href:`/${a.slug}`})),{title:"Quiénes somos",detail:"GEALAV: historia, misión y visión",href:"/nosotros"},{title:"Empresas del grupo",detail:"Directorio por provincia y actividad",href:"/estructura"},{title:"Contacto",detail:"Información y consultas comerciales",href:"/contacto"}];
const normalize=(v:string)=>v.normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase();
export default function SiteHeader(){
 const [menuOpen,setMenuOpen]=useState(false); const [query,setQuery]=useState(""); const [scrolled,setScrolled]=useState(false); const [hidden,setHidden]=useState(false); const [hovered,setHovered]=useState<string|null>(null);
 const dialog=useRef<HTMLDialogElement>(null); const input=useRef<HTMLInputElement>(null); const menuToggle=useRef<HTMLButtonElement>(null); const pathname=usePathname(); const reducedMotion=useReducedMotion();
 const {scrollY}=useScroll();
 // La navegación se retira al bajar para dejar la pantalla al contenido y vuelve en cuanto se sube.
 useMotionValueEvent(scrollY,"change",y=>{const previous=scrollY.getPrevious()??0;setScrolled(y>40);setHidden(y>320&&y>previous);});
 useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setMenuOpen(false);menuToggle.current?.focus();}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[menuOpen]);
 const results=searchItems.filter(item=>normalize(`${item.title} ${item.detail}`).includes(normalize(query)));
 return <><header className={`nav-shell${scrolled?" is-scrolled":""}${hidden&&!menuOpen?" is-hidden":""}`}><div className="nav-island"><Link className="brand" href="/" aria-label="GEALAV, inicio" onClick={()=>setMenuOpen(false)}><Image src="/images/logo.webp" width={210} height={55} alt="GEALAV · Grupo Empresarial de Alimentos y Aves" priority /></Link>
 <nav className="nav-links" aria-label="Navegación principal" onMouseLeave={()=>setHovered(null)}>{links.map(link=><Link key={link.label} href={link.href} className={pathname===link.href?"active":""} aria-current={pathname===link.href?"page":undefined} onMouseEnter={()=>setHovered(link.label)}>{hovered===link.label&&<m.span className="nav-hover" layoutId="nav-hover" transition={{type:"spring",stiffness:420,damping:34}} />}{link.label}</Link>)}</nav>
 <div className="nav-actions"><button className="nav-icon" aria-label="Buscar en el sitio" onClick={()=>{dialog.current?.showModal();input.current?.focus();}}><SearchIcon /></button><Link className="button button-small button-red nav-contact" href="/contacto">Contacto <Arrow /></Link><button ref={menuToggle} className="nav-icon nav-burger" aria-label={menuOpen?"Cerrar menú":"Abrir menú"} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)}><span className="burger" aria-hidden="true"><i /><i /></span></button></div></div></header>
 <AnimatePresence>{menuOpen&&<m.nav key="mobile-menu" id="mobile-menu" className="mobile-menu" aria-label="Navegación móvil" initial={reducedMotion?{opacity:0}:{clipPath:"circle(0% at 90% 5%)"}} animate={reducedMotion?{opacity:1}:{clipPath:"circle(160% at 90% 5%)"}} exit={reducedMotion?{opacity:0}:{clipPath:"circle(0% at 90% 5%)"}} transition={{duration:reducedMotion?0:.7,ease:[.22,1,.36,1]}}>
 <div className="mobile-menu-links">{links.map((link,index)=><m.div key={link.label} initial={{opacity:0,y:reducedMotion?0:40}} animate={{opacity:1,y:0}} transition={{duration:reducedMotion?0:.6,delay:reducedMotion?0:.18+index*.07,ease:[.22,1,.36,1]}}><Link href={link.href} aria-current={pathname===link.href?"page":undefined} onClick={()=>setMenuOpen(false)}><span><small>0{index+1}</small>{link.label}</span><Arrow /></Link></m.div>)}</div>
 <m.div className="mobile-menu-foot" initial={{opacity:0,y:reducedMotion?0:20}} animate={{opacity:1,y:0}} transition={{duration:reducedMotion?0:.5,delay:reducedMotion?0:.55}}><Link className="button button-yellow" href="/contacto" onClick={()=>setMenuOpen(false)}>Contacto y consultas <Arrow /></Link><span>GEALAV · La Habana, Cuba</span></m.div></m.nav>}</AnimatePresence>
 <dialog ref={dialog} className="site-dialog search-dialog" aria-labelledby="search-title" onClick={e=>{if(e.target===dialog.current)dialog.current?.close();}}><div className="dialog-content"><div className="dialog-heading"><h2 id="search-title">Buscar en GEALAV</h2><button className="icon-button" aria-label="Cerrar búsqueda" onClick={()=>dialog.current?.close()}><CloseIcon /></button></div><label className="search-field"><SearchIcon /><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Productos, empresas, contacto…" aria-label="Buscar contenido" /></label><p className="search-count" aria-live="polite">{query?`${results.length} ${results.length === 1 ? "resultado" : "resultados"}`:"Productos e información"}</p><div className="search-results">{results.map(item=><Link key={item.title} href={item.href} onClick={()=>dialog.current?.close()}><div><strong>{item.title}</strong><small>{item.detail}</small></div><Arrow /></Link>)}{results.length===0&&<p>No encontramos resultados. Prueba con «huevos», «aves» o «contacto».</p>}</div></div></dialog></>;
}
